config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games do
    resources :game_reviews, only: [:new, :create, :destroy]
  end
  resources :users do
    resources :user_reviews, only: [:new, :create, :destroy]
  end
  resources :game_sessions do
    resources :lobbies, only: [:new, :create, :destroy]

  end

  resources :lobbies, only: [:index]
  patch "lobbies/:id/accept", to: "lobbies#accept", as: :accept
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :game
  has_one_attached :photo
  has_many :lobbies, dependent: :destroy
  has_many :users, through: :lobbies, dependent: :destroy

  # Validations
  validates :is_smoke_free, :is_family_friendly, :has_drinks, :has_food, :is_recurrent, inclusion: { in: [true, false] }

  validates :date, :start_time, :address, :capacity, :session_name, presence: true
  # Geocoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def time
    start_time.strftime('%I:%M %p').to_s
  end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  def index
    if params[:query].present?
      @game_sessions = policy_scope(GameSession).joins(:game).where("games.name ILIKE ?", "%#{params[:query]}%")
    else
      @game_sessions = policy_scope(GameSession).order(created_at: :desc)
    end

    @markers = @game_sessions.geocoded.map do |game_session|
      {
        lat: game_session.latitude,
        lng: game_session.longitude,
        info_window: render_to_string(partial: "info_window", locals: { game_session: game_session }),
        image_url: helpers.image_url('marker.png')
      }
    end
  end

  def new
    @game_session = GameSession.new
    authorize @game_session
  end

  def create
    @game_session = GameSession.new(game_session_params)
    date = @game_session.date.to_datetime
    time = @game_session.start_time.to_datetime
    @game_session.starts_at = DateTime.new(date.year, date.month, date.day, time.hour, time.minute, time.second, 0)
    @game_session.user = current_user
    authorize @game_session
    if @game_session.save
      Lobby.create(game_session: @game_session, user: current_user, accepted: true)
      redirect_to game_session_path(@game_session)
    else
      render :new
    end
  end

  def show
    @game_session = GameSession.find(params[:id])
    @lobby = Lobby.where(game_session: @game_session, user: current_user).first || Lobby.new
    @markers = []
    @availability = @game_session.capacity - @game_session.lobbies.where(accepted: true).count
    authorize @game_session
    @session_data =
      {
        lat: @game_session.latitude,
        lng: @game_session.longitude,
        info_window: render_to_string(partial: "info_window", locals: { game_session: @game_session }),
        image_url: helpers.image_url('marker.png')
      }
    @markers.append(@session_data)
  end

  def edit
    @game_session = GameSession.find(params[:id])
    authorize @game_session
  end

  def update
    @game_session = GameSession.find(params[:id])
    authorize @game_session
    @game_session.update(game_session_params)
    redirect_to game_session_path(@game_session)
  end

  def destroy
    @game_session = GameSession.find(params[:id])
    authorize @game_session
    @game_session.destroy
    redirect_to game_sessions_path
  end

  private

  def game_session_params
    params.require(:game_session).permit(:description, :photo, :game_id, :session_name, :date, :start_time, :address, :is_smoke_free, :is_family_friendly, :has_drinks, :has_food, :capacity, :is_recurrent)
  end
end

app/views/game_sessions/_info_window.html.erb
<h2><%= game_session.session_name %></h2>
<p><%= game_session.address %></p>
<p><%= game_session.start_time.strftime("%b %e, %l:%M %p") %></p>
<%= button_to "Check it out!", game_session_path(game_session), method: :get, class: "btn btn-flat" %>

app/views/game_sessions/index.html.erb
<div class="container">
  <div class="search d-flex flex-column" >
  <h2 class="ml-4 mb-4 mt-4 text-warning font-weight-bold">Sessions</h2>
  <p  class="ml-4 mb-1">Find game sessions near you or search for a game.</p>
  <div class="search d-flex align-items-center p-3 mb-4">
    <div class="w-25">
      <%= form_tag game_sessions_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a game"
      %>
    </div>
    <div class="pl-3">
      <%= submit_tag "Search", class: "btn btn-flat" %>
    </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-between">
    <div class="cards col-7">
      <% @game_sessions.each do |game_session| %>
        <div class="card d-flex flex-column mb-2">
            <% if game_session.photo.attached? %>
              <%= cl_image_tag game_session.photo.key, class: "game-img"%>
            <% else %>
              <%= cl_image_tag game_session.game.photo.key, class: "game-img" %>
            <% end %>

          <div class="d-flex flex-column">
            <div class="d-flex align-items-center p-2 text-warning text-center" style="height: 100px;"><h6><%= game_session.session_name %></h6></div>
            <div class="d-flex flex-column justify-content-between" style="height: 260px;">
              <div class="font-weight-bold text-center"> <%= game_session.date.strftime("%A, %b %d") %></div>
              <div class="pl-4"><i class="fas fa-dice"></i> <%= link_to game_session.game.name, game_path(game_session.game), class: "text text-warning" %></div>
              <div class="pl-4"><i class="fas fa-map-marker-alt"></i> <%= game_session.address  %></div>
              <div class="p-1 pb-2 d-flex justify-content-around">
                <div>
                  <%= game_session.capacity %> <i class="fas fa-male"></i>
                </div>
                <% if game_session.is_smoke_free %>
                  <i class="fas fa-smoking-ban"></i>
                <% else %>
                  <i class="fas fa-smoking"></i>
                <% end %>

                <% if game_session.has_drinks %>
                  <i class="fas fa-cocktail"></i>
                <% end %>

                <% if game_session.has_food %>
                  <i class="fas fa-utensils"></i>
                <% end %>
              </div>

              <div class="pb-4 px-4">
                <%= link_to "See details", game_session_path(game_session.id), class: "btn btn-details" %>
              </div>
            </div>
          </div>

          <div class="btn-destroy">
            <% if policy(game_session).destroy? %>
              <%= link_to game_session_path(game_session), method: :delete, data: { confirm: "Are you sure you want to delete this session?" } do %>
                <button class = 'btn btn-danger'><i class="fas fa-trash-alt"></i></button>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div id="map" class="round-border col-5"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/game_sessions/new.html.erb
<div class="form-new row justify-content-center py-3">
  <div class="col-6">
    <h2 class="m-4 text-center text-warning font-weight-bold">Create session</h2>
    <%= simple_form_for @game_session do |f| %>
      <%= f.input :game_id, collection: Game.all %>
      <%= f.input :session_name %>
      <%= f.input :description %>
      <%= f.input :address %>
      <div class="d-flex">
        <%= f.input :date, as: :date, html5: true %>
        <%= f.input :start_time, as: :time %>
      </div>
      <p>Additional info:</p>
      <%= f.input :is_family_friendly, label: ('<i class="fa fa-child" aria-hidden="true"></i> Family Friendly').html_safe %>
      <%= f.input :is_smoke_free, label: ('<i class="fas fa-smoking-ban"></i> Smoke Free').html_safe %>
      <%= f.input :has_food, label: ('<i class="fas fa-utensils"></i> Food').html_safe %>
      <%= f.input :has_drinks, label: ('<i class="fas fa-cocktail"></i> Drinks').html_safe %>
      <%= f.input :is_recurrent, label: ('<i class="fa fa-calendar" aria-hidden="true"></i> Recurrent (E.g.: weekly or monthly)').html_safe %>
      <%= f.input :capacity, :label => "Spaces available" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create session", class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/game_sessions/show.html.erb
<div class="container">
  <div class="card d-flex flex-column my-4">
        <h2 class="m-4 text-center text-warning font-weight-bold"><%= @game_session.session_name %></h2>
        <div class="d-flex justify-content-center">
          <div class="ml-0 mt-1">
            <% if @game_session.user.photo.attached? %>
              <%= cl_image_tag @game_session.user.photo.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "standard_avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          </div>
          <div class="ml-1 d-flex flex-column align-items-center">
            <p class="mb-0">Hosted by:</p>
            <p> <%= link_to "#{@game_session.user.first_name} #{@game_session.user.last_name} ", user_path(@game_session.user), class: "text-warning" %></p>
          </div>
        </div>
      </div>
  <div class="d-flex justify-content-between">
    <div class="d-flex flex-column col-7">
      <div class="card mb-4 d-flex flex-column justify-content-betweent">
        <% if @game_session.photo.attached? %>
          <%= cl_image_tag @game_session.photo.key, class: "session-img" %>
        <% else %>
          <%= cl_image_tag @game_session.game.photo.key, class: "session-img" %>
        <% end %>

        <div class="pb-4 px-4">
          <h5 class="my-3">Details</h5>
          <p><%= @game_session.description%></p>
          <div><i class="fas fa-dice"></i> <%= link_to @game_session.game.name, game_path(@game_session.game), class: "text text-warning" %></div>
          <div class="d-flex justify-content-between align-items-center pt-2", style="width: 75px;">
            <% if @game_session.is_smoke_free %>
              <i class="fas fa-smoking-ban"></i>
            <% else %>
              <i class="fas fa-smoking"></i>
            <% end %>

            <% if @game_session.has_drinks %>
              <i class="fas fa-cocktail"></i>
            <% end %>

            <% if @game_session.has_food %>
              <i class="fas fa-utensils"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card d-flex flex-column justify-content-between">
        <h5 class="pt-4 pl-4">Attendees</h5>
        <div class="pb-4 pl-4">
          <% @game_session.lobbies.each do |lobby| %>
            <% if lobby.accepted %>
              <div class="d-flex py-2">
                <div>
                  <% if lobby.user.photo.attached? %>
                    <%= cl_image_tag lobby.user.photo.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% else %>
                    <%= image_tag "standard_avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
                </div>
                <div class="d-flex align-items-center pl-1">
                  <%= link_to "#{lobby.user.first_name} #{lobby.user.last_name} ", user_path(lobby.user), class: "text-warning" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if current_user == @game_session.user %>
        <div class="card d-flex flex-column justify-content-between mt-4">
          <h5 class="pt-4 pl-4">Pending attendees</h5>
          <div class="pb-4 pl-4">
            <% @game_session.lobbies.each do |lobby| %>
              <% if !lobby.accepted %>
                <div class="d-flex py-2">
                  <div>
                    <% if lobby.user.photo.attached? %>
                      <%= cl_image_tag lobby.user.photo.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                    <% else %>
                      <%= image_tag "standard_avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                    <% end %>
                  </div>
                  <div class="d-flex align-items-center justify-content-between px-4 w-100">
                    <div>
                      <%= link_to "#{lobby.user.first_name} #{lobby.user.last_name} ", user_path(lobby.user), class: "text-warning" %>
                    </div>
                    <div>
                      <%= simple_form_for lobby, url: accept_path(lobby), method: :patch do |f| %>
                        <%= f.submit "Approve", class: "btn btn-flat" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="d-flex flex-column round-border col-5">
      <div class="card p-4">
        <div class="d-flex font-weight-bold">
          <p><%= @game_session.date.strftime("%A, %b %d")%></p>
          <p class="px-1">@</p>
          <p><%= @game_session.start_time.strftime("%l:%M %p")%></p>
        </div>
        <p><i class="fas fa-map-marker-alt"></i> <%= @game_session.address %></p>
        <div class="d-flex justify-content-between">
          <p><%= @availability %> spots left</p>
          <div class="form px-4 pb-4">
            <% if current_user.lobbies.where(game_session: @game_session).empty? %>
              <%= simple_form_for [@game_session, @lobby] do |f| %>
                <%= f.submit "Ask to join", class: "btn btn-flat" %>
              <% end %>
            <% else %>
              <%= link_to game_session_lobby_path(@game_session, @lobby), method: :delete, data: { confirm: "Are you sure you want to leave this game session?" } do %>
                <button class = 'btn btn-flat'>Leave</button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <div id="map" class="round-border my-4"
          style="width: 100%; height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>